### ISSUE TITLE
Totally "Mute" when I wake MAC from sleep

### ISSUE THREAD

**Issue by Faasteer** [romankisil/eqMac2#12]
Hello,
First of all, thank you for your work that you are doing here. But I have a really annoying problem with this new version. Whenever I wake up my MAC from sleep, I lose all the sound. Then I have to manually select the audio output and everything will go back to normal. It's really frustrating, I'm using power-saving and background music, so I have to do this a hundred times a day.

My configuration is:
Mac Mini, Late 2012 (Intel Core i7 @2,3Ghz, 16GB RAM, 512GB SSD + 1TB HDD)

Thank you for the answer and the solution to the problem.

**Comment by Faasteer** [comment]
Oh, I forgot to mention that, in this case it's a standard integrated sound card. Analog output, 3.5mm jack for "headphones".

**Comment by romankisil** [comment]
Thanks for the Bug report, I have noticed this behaviour sometimes myself. Will hopefully fix in the next update

**Comment by Faasteer** [comment]
Thank you for a quick response. I will look forward to this update. On my side it's really every time I wake up my MAC. 

PS: This version is a huge move forward, compared to the old version. You're the best! ;)

**Comment by jameyers4** [comment]
I'm going out on a limb just a bit, but this may be same issue (or closely related) to the bug I filed a couple of days ago.  Hopefully it is, and you get two for the fix of one....

**Comment by romankisil** [comment]
@jameyers4 you mean issue #6 ?
In that issue you mentioned that app loses reference to your device, but you haven't mentioned that sound is not playing anymore. I thought it plays from some other device. Can I get more details on this?

**Comment by jameyers4** [comment]
Away from Mac right now - though I'd say audio stops.  If I open audio
settings, eqMac2  selected as output dev, no audio plays.  Reselect BT
device, audio starts again.  Best I can recall without being at Mac.

If there specific info you would need?

Best,

Jeff

Please excuse brevity and typos, as this was sent from a mobile device.

**Comment by peptoni** [comment]
Same behaviour here:  no sound after coming back from sleep.  After sleep, on Sound preferences panel, output is correctly set to "eqMac2".  I have to select "Internal Speakers" and it automatically goes back to "eqMac2", then sound comes back.
iMac 27" 2017 with 24 Gb RAM, 256 SSD, Radeon Pro 575 4 Gb.  macOS Sierra 10.12.6.

**Comment by romankisil** [comment]
fixed in a31e2bc8c939d7a0b08daae8a31913b3e9b1e5b4

**Comment by Faasteer** [comment]
I'm sorry to say so, but in my case, it's not fixed. I tried updating to this new version, no change. Then I completely removed the entire program, restarted MAC, re-installed eqmac and no difference. Still the same behavior. Immediately after my MAC goes into sleep, I will wake him up and the sound will disappear.

It's completely the same scenario as in my original post or peptoni post.

**Comment by romankisil** [comment]
Yeah other people have reported it as well. Sorry guys it's just not happening quite often in my case so it's hard to debug. Please refer to #27 for updates on this issue. Thanks and excuse me for the bug.

**Comment by peptoni** [comment]
Sorry?????  THANK YOU, for a wonderful work!!!!  Please, please, never again apologize.

**Comment by Faasteer** [comment]
Peptoni has right! I'm just trying to help. And as I wrote in the second post that you gave me. I think it's bigger problem, because competing software shows exactly the same error. :)

**I quote myself (it's weird):**
I also have interesting information, or I think so. I tried to compare your program with "BOOM2", I installed the trial version and guess what? Exactly the same problem. So I think this will be something bigger...

And by the way, I also have monitors with audio input. Off in the monitor, but MAC shows the playback option. So I think it has a connection with the jameyers4 post.

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
